# Generated by Django 3.1.2 on 2020-10-25 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.CharField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подзаголовок')),
                ('slug', models.CharField(max_length=255, unique=True, verbose_name='URL')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Фото')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('developer', models.CharField(blank=True, max_length=225, verbose_name='Кто ты')),
                ('skills', models.TextField(blank=True, verbose_name='Навыки члена команды')),
                ('age', models.PositiveIntegerField(blank=True, verbose_name='Возраст')),
                ('telegram', models.CharField(blank=True, max_length=225, verbose_name='Telegram ссылка')),
                ('instagram', models.CharField(blank=True, max_length=225, verbose_name='Instagram ссылка')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spring.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команда',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подзаголовок')),
                ('slug', models.CharField(max_length=255, unique=True, verbose_name='URL')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Фото')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('photo', models.ImageField(blank=True, upload_to='', verbose_name='Фото')),
                ('tools_used_one', models.CharField(blank=True, max_length=125, verbose_name='Используемый инструмент #1')),
                ('tools_used_two', models.CharField(blank=True, max_length=125, verbose_name='Используемый инструмент #2')),
                ('tools_used_three', models.CharField(blank=True, max_length=125, verbose_name='Используемый инструмент #3')),
                ('tools_used_four', models.CharField(blank=True, max_length=125, verbose_name='Используемый инструмент #4')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spring.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подзаголовок')),
                ('slug', models.CharField(max_length=255, unique=True, verbose_name='URL')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Фото')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('client_name', models.CharField(blank=True, max_length=255, verbose_name='Имя заказчика')),
                ('project_cat', models.CharField(blank=True, max_length=255, verbose_name='Технологии используемые в проекте')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Дата создания проекта')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spring.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Портфолио',
                'verbose_name_plural': 'Портфолио',
            },
        ),
    ]
