# Generated by Django 3.1.2 on 2020-10-26 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Helpbiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('image', models.ImageField(upload_to='', verbose_name='Фото')),
                ('backg', models.CharField(max_length=155, verbose_name='Background')),
            ],
            options={
                'verbose_name': 'Сферы бизнеса',
                'verbose_name_plural': 'Сферы бизнеса',
            },
        ),
        migrations.AddField(
            model_name='service',
            name='backg',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Background'),
        ),
    ]
