# Generated by Django 3.1.2 on 2020-10-26 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spring', '0003_auto_20201026_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='speed',
            field=models.CharField(blank=True, help_text='Выбрать один из скоростей: 0.2, 0.4, 0.6', max_length=50, null=True, verbose_name='Скорость выхода поста'),
        ),
    ]
