# Generated by Django 3.1.2 on 2020-10-26 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spring', '0004_portfolio_speed'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpbiz',
            name='speed',
            field=models.CharField(blank=True, help_text='Выбрать один из скоростей: .2, .4, .6, .8, 1.2, 1.4, 1.6, 1.8, 2, 2.2', max_length=50, null=True, verbose_name='Скорость выхода поста'),
        ),
        migrations.AlterField(
            model_name='helpbiz',
            name='backg',
            field=models.CharField(help_text='Выбрать один из цветов для фона: cd2, cd3, cd4, cd5, cd6, cd7, cd8, cd9, cd10, cd11', max_length=50, verbose_name='Background карточек на главной стр'),
        ),
    ]
