# Generated by Django 3.1.2 on 2020-10-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spring', '0005_auto_20201026_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpbiz',
            name='speed',
            field=models.CharField(blank=True, help_text='Выбрать один из скоростей: 0.2, 0.4, 0.6, 0.8, 1.2, 1.4', max_length=50, null=True, verbose_name='Скорость выхода поста'),
        ),
    ]
