# Generated by Django 3.1.2 on 2020-10-26 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spring', '0007_statistic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statistic',
            options={'verbose_name': 'Блок Нашей Статистики', 'verbose_name_plural': 'Блок Нашей Статистики'},
        ),
    ]
